${
def fact(Int n) => Int {
    if n == 0 then return 1; 
    else return n * fact(n-1);
    done
}

let Int input;
print("Input: ");
input = readi();

if input < 0 then 
    print("Hasta luego!");
    exit(0);
done 

print("Resultado calculado!");
exit(fact(input));
}$

print(
    "Caracteres: %c %c%cNumeros: %i %i%cTextos: %s %s%c", 
    chars=['A', '\t', '\n', '\n', '\n'],
    ints=[42, -69],
    strings=["Hello", " world!"],
    end="Final"
);