execonce "Math.mac";
execonce "String.mac";

let Float n;
let Char option;

while True do 
	print("Indique el numero en punto flotante no negativo: ");
	n = readf();

	if n < 0.0 then 
		print("No se permiten numeros negativos");
		continue;
	elsif n == 0.0 then 
		print("sqrt(0) = 0");
	else
		print("sqrt(%f) = %f", floats=[n, sqrt(n)]);
	done

	print("Desea calcular otra raiz? [Y/n] ");
	option = readc();
	if option == 'n' || option == 'N' then 
		print("Hasta luego!");
		break;
	done 
done
