dec F(
  Int a, 
  Char @c, 
  ^Int khe = new Int, 
  String ola = "k ase?", 
  Bool[1] b = [False]
);

if (True) then
  def g() {
      F(1, '0');
      return;
  }
  def F(Int a, Char @c, ^Int khe, String ola, Bool[1] b) {
      g();
      F(1, '0', ola = "ke no ase?");
      return;
  }
done

def F(Int a, Char @c, ^Int khe, String ola, Bool[1] b) { }

dec H();

if (True) then 
  if (True) then 
    H();
    def H() { }
  done 
  def H() { }
done 
def H() { }
